import type { Metadata } from "next";
import localFont from "next/font/local";
import { Poppins } from 'next/font/google';

import { Toaster } from "@/components/ui/toaster";
import { ModalProvider } from "@/providers/modal-provider";
import { GoogleOAuthProvider } from "@react-oauth/google";

import "@livekit/components-styles"
import "./globals.css";

const lazydog = localFont({
  src: "./Lazydog.otf",
  variable: '--font-lazydog',
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: "Kuliah di Luar Yuk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${lazydog.variable} font-sans`}>
        <GoogleOAuthProvider clientId={process.env.GOOGLE_CLIENT_ID!}>
          <Toaster />
          <ModalProvider />
          {children}
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}